name: My First Workflow

on:
  push:
    branches: 
      - main
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: boolean
        required: true
    
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "👋 Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: List files in repository
        run: |
          echo "The repository ${{github.repository}} contains the following files:"
          tree
      - name: Print the inputs
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Tags: ${{ inputs.tags }}"
          echo "Environment: ${{ inputs.environment }}"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        
      
